### PR TITLE
Issues #182 (part), #254. Replace ForgeRock brocken repo

### PR DESCRIPTION
**Pull request by dimipapadeas**
We hosted the ForgeRock artifacts at European Dynamics public Nexus repository.

### CODE REVIEW

**Comment by rogers492** [comment]
Hi @dimipapadeas If you need a reviewer for this then I suggest you assign @tg4444 or @lmika-bom

**Comment by dimipapadeas** [comment]
@lmika-bom  Could you please review and merge this Pull request?
Thank you in advance.

**Comment by rogers492** [comment]
Ok Sean @cmteam-metoffice we're good to go with the 3.14.8 Release.

**Comment by dimipapadeas** [comment]
We have notice that the Jenkins build somehow still tries to fetch artifacts from ForgeRock, even though their repositories are commented-out in the main pom.xml.
@ShaunDAdams @lmika-bom  Are you aware of anything Jenkins-related that may cause this?

**Comment by lmika-bom** [comment]
Managed to recreate the issue found on Jenkins on my dev workstation.  Removing the forgerock artefacts from the local Maven repository (~/.m2/repository/org/forgerock) seemed to have resolved it.

Is there a way to do this in Cloudbee's Jenkins?

**Comment by dimipapadeas** [comment]
@ShaunDAdams  if is not possible to delete the ForgeRock artifacts manualy as @lmika-bom said, we can try (just once) to build with "-U" option.
This will force maven to delete all mentioned artifacts and re-fetch them, so they will be downloaded from our own repo.

**Pull request merged**
